services:
  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: meubanco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    volumes:
      - ./data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql # opcional para script
  postgres:
    image: postgres:15
    container_name: meu-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meubanco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    volumes:
      - ./data:/var/lib/postgresql/data